### ISSUE TITLE
X error of failed request: BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by w45yrtfgdfefrt** [ClioPatria/ClioPatria#46] opened 2017-03-31 08:02 UTC
I've followed the [installation instructions](https://github.com/ClioPatria/ClioPatria#installation) to install ClioPatria

- git clone https://github.com/ClioPatria/ClioPatria.git
- cd ClioPatria
- git submodule update --init web/yasqe
- git submodule update --init web/yasr
- ./configure
- ./run.pl

but what I get is an endless, never halting, stream of errors like these

```
ERROR: ~/ClioPatria/config-enabled/debug.pl:48:
	nil: X-error
X error of failed request: BadWindow (invalid Window parameter)
Major opcode of failed request: 25 (X_SendEvent)
Minor opcode of failed request: 0
Resource id in failed request:  0x21105e8
Serial number of failed request: 4385
X error of failed request: BadWindow (invalid Window parameter)
Major opcode of failed request: 8 (X_MapWindow)
Minor opcode of failed request: 0
Resource id in failed request:  0x5e0001b
Serial number of failed request: 4386
X error of failed request: BadWindow (invalid Window parameter)
Major opcode of failed request: 12 (X_ConfigureWindow)
Minor opcode of failed request: 0
Resource id in failed request:  0x5e0001b
Serial number of failed request: 4387
X error of failed request: BadWindow (invalid Window parameter)
Major opcode of failed request: 3 (X_GetWindowAttributes)
Minor opcode of failed request: 0
Resource id in failed request:  0x5e0001b
Serial number of failed request: 4388
Message: debug_mode(on)
Message: error(pce(x_error,[@nil]),send(@prolog_warnings,expose))
Message: error(pce(x_error,[@nil]),send(@prolog_warnings,expose))
```

how do I fix this?

**Comment by jrvosse** [comment] 2017-03-31 09:25
On 03/31/2017 10:02 AM, w45yrtfgdfefrt wrote:

> but what I get is an endless, never halting, stream of errors like these
>
> ```
> ERROR: ~/ClioPatria/config-enabled/debug.pl:48:
> 	nil: X-error
> X error of failed request: BadWindow (invalid Window parameter)
> Major opcode of failed request: 25 (X_SendEvent)
> Minor opcode of failed request: 0

Something goes wrong with the X11 setup as debug.pl tries to set up a graphical editor in line 48.

> how do I fix this?

This looks like you are trying to run Cliopatria on a remote *nix server without your environment variable DISPLAY properly set...

Does login with "ssh -X" help? If not, do other X11 applications work ok?

Hope this helps,

Jacco

**Comment by w45yrtfgdfefrt** [comment] 2017-03-31 10:19
Yeah I'm not using any desktop environment. Running `../ClioPatria/configure --without-debug` seems to fix the issue, although I still get errors for jQuery

```
ERROR: ~/ClioPatria/lib/http/cp_jquery.pl:33:
	source_sink `library(http/jquery)' does not exist
Warning: ~/ClioPatria/lib/http/cp_jquery.pl:33:
	Goal (directive) failed: cp_jquery:use_module(library(http/jquery))
ERROR: ~/ClioPatria/lib/http/cp_jquery.pl:36:
	setting `version' does not exist
Warning: ~/ClioPatria/lib/http/cp_jquery.pl:36:
	Goal (directive) failed: cp_jquery:set_setting(jquery:version,2.1.3.min)
```

Should I use `./daemon.pl` instead of `./run.pl`?

**Comment by jrvosse** [comment] 2017-03-31 10:47
On 03/31/2017 12:19 PM, w45yrtfgdfefrt wrote:
> Yeah I'm not using any desktop environment. Running `../ClioPatria/configure --without-debug` seems to fix the issue, although I still get errors for jQuery
>
> ```
> ERROR: ~/ClioPatria/lib/http/cp_jquery.pl:33:
> 	source_sink `library(http/jquery)' does not exist

This looks like a different and unrelated problem. Which swi prolog version are you using?
The file corresponding to library(http/jquery) file has been added in May 2015...
My experience is that if you want to run ClioPatria, the swipl package of many linux distributions is too outdated.
I would recommend installing you own, up to date version of swipl, or even compile yourself from git.
See http://www.swi-prolog.org/Download.html for details.

Success,

Jacco

**Comment by w45yrtfgdfefrt** [comment] 2017-03-31 11:08
> Which swi prolog version are you using?

https://packages.debian.org/jessie/swi-prolog

**Comment by jrvosse** [comment] 2017-03-31 13:56
check, that seems very old (v6.6.6 is eval anyway :-)
I would strongly recommend switching to install your own, more recent version.
Just take the devel version at http://www.swi-prolog.org/download/devel 
or compile from the git source https://github.com/SWI-Prolog/swipl-devel

**Comment by bghnjkjiu8y7utytg** [comment] 2017-03-31 15:24
recompiled everything, now have this

```
$ swipl --version
SWI-Prolog version 7.5.2 for x86_64-linux
```

and no jQuery errors anymore. Still get the same errors about X when configuring my project with debug *on*.
Could you please close this issue?

**Comment by jrvosse** [comment] 2017-03-31 15:41
I cannot reproduce your problem. Can you check if other X11 applications do work?
You say you are not using any desktop environment, which is fine.
But this still could mean that you want an X11 connection, but your X11 setup could be broken and you need to fix it. This you could check by running other X11 applications in the same shell you use to start ClioPatria.
Or you do not want X11 and thus your DISPLAY environment variable should not be set. In that case, just "unset DISPLAY" in your shell should tell swipl to not even try to open an X11 connection.

**Comment by bghnjkjiu8y7utytg** [comment] 2017-03-31 16:55
The variable was set to `:0`. Now it's working fine with no errors.

**Closed** 2017-08-21 15:27 UTC
